### ISSUE TITLE
给 NAS 一个漂亮的封面 | 杰森的博客

### ISSUE THREAD

**Issue by huqinlon** [huqinlon/wang-luo-bi-ji#4]
书接上回，我搭建了一整套 NAS 系统，但是前端 UI 过于丑陋，因此这次找了 [Dashy](https://github.com/Lissy93/dashy) 作为 NAS 的前端封面。

直接上成品图（一张截图放不下）：  
![](1.png)

![](2.png)

[](#安装-Dashy "安装 Dashy")安装 Dashy
--------------------------------

新增配置文件夹

```plaintext
mkdir /etc/dashy
```

Docker-compose 文件

```plaintext
version: "3.8"
services:
  dashy:
    image: lissy93/dashy
    container_name: Dashy
    volumes:
      - /etc/dashy/conf.yml:/app/public/conf.yml
    ports:
      - 4000:80
    environment:
      - NODE_ENV=production
      - UID=0
      - GID=0
    restart: always
    healthcheck:
      test: [ 'CMD', 'node', '/app/services/healthcheck' ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
```

> `/etc/dashy/conf.yml` 为本地配置文件路径

启动 Dashy

```plaintext
docker-compose up -d
```

[](#配置-Dashy "配置 Dashy")配置 Dashy
--------------------------------

打开浏览器，访问`http://ip:4000`

点击设置进行配置

![](3.png)

配置主要分为父`Section`和子`Item`两块内容

左上角以及导航栏需点击`Edit Page Info`修改  
![](4.png)

图标配置

> 有些项目可以直接获取图标，有些不行

1.  直接获取，填入`hl-项目名称小写`  
    ![](5.png)
    
2.  [fontawesome.com](https://fontawesome.com/icons/democrat?s=solid) 免费图标。  
    ![](6.png)
      
    ![](7.png)
    

> `fa-solid` 改成 `fas` 就行。

修改完成后，点击`Save to Disk`保存，不知道为什么保存有延迟且可能失败，多试几次就行。

[](#配置分享 "配置分享")配置分享
--------------------

> 这边仅仅是我个人的配置，仅供参考。

```yaml
appConfig:
  theme: high-contrast-dark
  layout: auto
  iconSize: large
  language: cn
  startingView: default
  defaultOpeningMethod: newtab
  statusCheck: true
  statusCheckInterval: 0
  faviconApi: allesedv
  routingMode: history
  enableMultiTasking: false
  widgetsAlwaysUseProxy: false
  webSearch:
    disableWebSearch: false
    searchEngine: duckduckgo
    openingMethod: newtab
    searchBangs: {}
  enableFontAwesome: true
  enableMaterialDesignIcons: false
  hideComponents:
    hideHeading: false
    hideNav: false
    hideSearch: false
    hideSettings: false
    hideFooter: false
  auth:
    enableGuestAccess: false
    users:
      - user: admin
        hash: D82494F05D6917BA02F7AAA29689CCB444BB73F20380876CB05D1F37537B7892
        type: admin
    enableKeycloak: false
  showSplashScreen: false
  preventWriteToDisk: false
  preventLocalSave: true
  disableConfiguration: false
  allowConfigEdit: true
  enableServiceWorker: false
  disableContextMenu: false
  disableUpdateChecks: false
  disableSmartSort: false
  enableErrorReporting: false
pageInfo:
  title: 杰森的NAS
  description: 心焰不熄，吾道不绝 !
  navLinks:
    - title: GitHub
      path: https://github.com/Lissy93/dashy
      target: newtab
    - title: Documentation
      path: https://dashy.to/docs
      target: newtab
  footerText: ""
sections:
  - name: 系统管理
    icon: fas fa-server
    items:
      - title: V2rayA
        description: 透明代理管理
        icon: fas fa-swords
        url: http://10.0.0.1:2017
        target: newtab
        id: 0_125825_vraya
      - title: Netdata
        description: 系统监控管理
        icon: hl-netdata
        url: >-
          http://10.0.0.1:19999/#menu_system_submenu_cpu;after=0;before=0;theme=slate;update_always=true;utc=Asia/Shanghai
        target: newtab
        id: 1_125825_netdata
      - title: Filebrowser
        description: 文件管理器
        icon: hl-filebrowser
        url: http://10.0.0.1:8081
        target: newtab
        id: 2_125825_filebrowser
      - title: Alist
        description: 网盘管理器
        icon: fas fa-cloud
        url: http://10.0.0.1:5244/
        target: newtab
        id: 3_125825_alist
      - title: Prowlarr
        description: 索引器管理器
        icon: hl-prowlarr
        url: http://10.0.0.1:80/prowlarr/
        target: newtab
        id: 4_125825_prowlarr
      - title: Bazarr
        description: 字幕管理器
        icon: hl-bazarr
        url: http://10.0.0.1:80/bazarr/
        target: newtab
        id: 5_125825_bazarr
      - title: Chinesesubfinder
        description: 中文字幕管理器
        icon: fas fa-closed-captioning
        url: http://10.0.0.1:80/chinesesubfinder/
        target: newtab
        id: 6_125825_chinesesubfinder
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
  - name: 影音系统
    icon: fas fa-film
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: Miniflux
        description: RSS 阅读器
        icon: hl-miniflux
        url: http://10.0.0.1:8288
        target: newtab
        id: 0_127806_miniflux
      - title: Emby
        description: 影音播放器
        icon: hl-emby
        url: http://10.0.0.1:8096/
        target: newtab
        id: 1_127806_emby
      - title: Ombi
        description: 影音搜索前端
        icon: hl-ombi
        url: http://10.0.0.1:3579/
        target: newtab
        id: 2_127806_ombi
      - title: Sonarr
        description: 电视剧管理器
        icon: hl-sonarr
        url: http://10.0.0.1:80/sonarr/
        target: newtab
        id: 3_127806_sonarr
      - title: Radarr
        description: 电影管理器
        icon: hl-radarr
        url: http://10.0.0.1:80/radarr/
        target: newtab
        id: 4_127806_radarr
      - title: Lidarr
        description: 音乐管理器
        icon: hl-lidarr
        url: http://10.0.0.1:80/lidarr/
        target: newtab
        id: 5_127806_lidarr
      - title: Readarr
        description: 电子书管理器
        icon: hl-readarr
        url: http://10.0.0.1:80/readarr/
        target: newtab
        id: 6_127806_readarr
  - name: 下载管理
    icon: fas fa-download
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: Qbittorrent
        description: BT/PT 下载器
        icon: hl-qbittorrent
        url: http://10.0.0.1:80/qbt/
        target: newtab
        id: 0_118063_qbittorrent
      - title: Nzbget
        description: Nzb 下载器
        icon: hl-nzbget
        url: http://10.0.0.1:80/nzbget/
        target: newtab
        id: 1_118063_nzbget
      - title: Amule
        description: Ed2k 下载器
        icon: fas fa-democrat
        url: http://10.0.0.1:4711/
        target: newtab
        id: 2_118063_amule
      - title: Resilio-sync
        description: Bt sync 下载器
        icon: hl-resiliosync
        url: http://10.0.0.1:8888/gui/
        target: newtab
        id: 3_118063_resiliosync
      - title: IPFS
        description: 去中心化储存网络节点
        icon: fas fa-chart-network
        url: http://10.0.0.1:5001/webui
        target: newtab
        id: 4_118063_ipfs
      - title: I2pd
        description: I2p网络节点
        icon: fas fa-eye-slash
        url: http://10.0.0.1:7070
        target: newtab
        id: 5_118063_ipd
      - title: Rsshub
        description: RSS 生成器
        icon: hl-rsshub
        url: http://10.0.0.1:80/rsshub/
        target: newtab
        id: 6_118063_rsshub
```

[](#总结 "总结")总结
--------------

这封面不比之前的那个好看多了，2333。
